name: media2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.2
  cloud_firestore: ^5.4.3
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  cached_network_image: ^3.4.1
  video_player: ^2.9.1
  path: ^1.9.0
  url_launcher: ^6.3.1
  mime: ^1.0.6
  image: ^4.1.7
  video_thumbnail: ^0.5.3
  get_thumbnail_video: ^0.7.3
  http: ^1.2.2
  pdfx: ^2.5.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
